---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-chef-supermarket
description: Install chef-supermarket through ansible
tags:
  - ansible
  - ansible-role
  - chef-supermarket
github: {}
