---
- name: Include ansible_distribution and ansible_os_family tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: configure - supermarket-ctl reconfigure
  become: true
  become_user: root
  shell: "supermarket-ctl reconfigure"

- name: configure - generate supermarket config
  register: cntlm_conf
  template:
    src: templates/supermarket.json.j2
    dest: /etc/supermarket/supermarket.json
    owner: root
    group: root
    mode: 0644

- name: configure - supermarket-ctl reconfigure
  become: true
  become_user: root
  shell: "supermarket-ctl reconfigure"
